# To configure this workflow:
# 1. Set up a secret in your repository named AZURE_WEBAPP_PUBLISH_PROFILE with the value of your Azure publish profile.
# 2. Change the value for AZURE_WEBAPP_NAME, AZURE_WEBAPP_PACKAGE_PATH and NODE_VERSION set as environment variables  (below).
on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: yc2021-todo
  NODE_VERSION: '14.x'

jobs:
  build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Put secrets in .env
        env:
          HOST: ${{ secrets.AZURE_DB_HOST }}
          USER: ${{ secrets.AZURE_DB_USER }}
          PW: ${{ secrets.AZURE_DB_PW }}
        run: echo -e "AZURE_DB_HOST=$HOST\nAZURE_DB_USER=$USER\nAZURE_DB_PW=$PW\n" > .env

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jorenb/yc2021-todo:${{ github.sha }}

  deploy:
    name: Deploy to azure web app
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: registry.hub.docker.com/jorenb/yc2021-todo:${{ github.sha }}
