name: Verify changes

on: pull_request

jobs:
  verify:
    name: Verify changes
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Put secrets in .env
        run: echo -e "DB_USER=joren\nDB_PW=grapefruits" > .env

      - name: Run tests
        run: docker-compose -f docker-compose.yml -f docker-compose-ci.yml up --exit-code-from app
